# Generated by Django 2.2.6 on 2019-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20191022_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='school_app.Tag'),
        ),
        migrations.DeleteModel(
            name='CourseTags',
        ),
    ]
