# Generated by Django 2.2.6 on 2019-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_auto_20191024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
