# Generated by Django 2.2.6 on 2019-11-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_auto_20191101_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtocourse',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
