# Generated by Django 2.2.6 on 2019-11-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_assignedtocourse_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.Room'),
        ),
    ]
