# Generated by Django 2.2.6 on 2019-11-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_auto_20191129_1813'),
        ('school_app', '0010_auto_20191129_1740'),
    ]

    operations = [
    ]
