# Generated by Django 2.2.6 on 2019-11-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_merge_20191129_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='term',
            name='dateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='repeatIn',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.User')),
            ],
        ),
    ]
