# Generated by Django 2.2.6 on 2019-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_auto_20191129_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
