# Generated by Django 2.2.6 on 2019-11-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0013_term_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='dateEnd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
