# Generated by Django 2.2.6 on 2019-11-30 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0014_auto_20191130_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='term',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
